import { CONTENT_ACCESS_TABS, BURGER_MENU_KEY } from "./constants";
import { ROUTES } from "./routes";

export const CONTENT_ACCESS_MAP = {
  [CONTENT_ACCESS_TABS.CONTENT]: {
    allow: ["SERIES_MANAGEMENT", "MODULE_SHARING", "MODULE_DEVELOPMENT"]
  },
  [CONTENT_ACCESS_TABS.LEARNERS]: {
    allow: [
      "LEARNER_MANAGEMENT",
      "GROUP_ADMINISTRATION",
      "CONTENT_SHARING_VIA_GROUP",
      "COORDINATE_PARTNER_GROUPS"
    ]
  },
  [CONTENT_ACCESS_TABS.ANALYTICS]: {
    allow: [
      "SERIES_VIEW_ANALYTICS",
      "MODULE_VIEW_ANALYTICS",
      "MANAGER_VIEW_ANALYTICS",
      "GROUP_VIEW_ANALYTICS"
    ]
  },
  [CONTENT_ACCESS_TABS.REVIEWS]: {}
};

export const ROUTES_ACCESS_MAP = {
  [ROUTES.RULES]: {
    allow: ["VIEW_AUTOMATION_RULES", "EDIT_AUTOMATION_RULES", "MANAGE_AUTOMATION_RULES"],
    features: ["ruleAutomationEnabled"]
  },
  [BURGER_MENU_KEY.VIEW_PMH]: {
    allow: ["LEARNING_SITE_CUSTOMIZATIONS"]
  },
  [BURGER_MENU_KEY.MANAGE_TAGS]: {
    allow: ["CREATE_EDIT_TAGS", "APPLY_TAGS"],
    features: ["taggingEnabled"]
  }
};
